spring.application.name=track-my-vehicle-auth-server

server.port=9000
server.servlet.context-path=/track-my-vehicle-auth

spring.datasource.url=jdbc:postgresql://ep-solitary-frost-ao2zo5hv-pooler.c-2.ap-southeast-1.aws.neon.tech/auth-db
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jfH6DFKU3xRA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.properties.hibernate.dialect=org.postgresql.Driver
spring.jpa.hibernate.properties.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

app.security.white.list=api/v1/public/**,api/v1/auth/**

app.email.domain.name=gmail.com

# jwt properties
app.jwt.token.issuer=dev.orion.auth
app.jwt.token.access.life=30
app.jwt.token.refresh.life=240
app.jwt.private-key-path=classpath:certs/private-key.pem